waldo1001/crs-al-language-extension

- src/NAVObject.ts
I got a lot of errors when using the renaming/reorganize feature on our solution. It seems as all comes down to issues with special characters.
Several issues that I'm trying to solve here:
1. Several special characters not supported
2. Object names is only surrounded with " if needed
3. Objects gets renamed if containing some illegal characters, even though only file needs that. I want object name to remain.
I've tried to solve above issues, and it now runs fine on my 600+ objects. I might have missed some special characters, but at least they only need to be added on one place now.
I have not changed the naming of profile and pagecustomization, since I had not test objects for those, but probably the same change could be done there.
> Solve renaming issues with special characters

- src/NAVObject.ts
- src/WorkspaceFiles.ts
- src/test/NAVObject.test.ts
- src/test/NAVTestObjectLibrary.ts
It's a challenge to create a regex that matches all possible names of objects. 
Now I've added all printable ASCII characters except ". That should work for files converted from C/AL, but could still miss some Unicode characters if used... Don't really know how to solve that properly.
Anyway, I added a bit to your new test to also check that some characters as µ and åäö still exists after fixing filename.
The test runs fine for me now.
What do you think?
> Another go on "Solve renaming issues with special characters"

- snippets/fromAlExtension/al.json
who wants to create a trigger without brackets?
> Remove brackets from ttrigger placeholder

- package.json
- snippets/Test.json
I got tired of typing the same every time I write test cases.
I've added a single snippet, which adds the following snippet:
```
[Test]
procedure "SalesHeader.Released.ErrorOnEditCustomer"()
begin
// [GIVEN] SalesHeader 
// [WHEN] Released 
// [THEN] ErrorOnEditCustomer 
end;
```
> Test snippets

- src/NAVObject.ts
- src/StringFunctions.ts
This fixes a runtime issue with reports where BC is expecting request page field names like ChosenOutputMethod to be without quotation marks.
> Fix for single-word field names in quotation

- src/NAVObject.ts
- src/StringFunctions.ts
So turns out my fix for single-word field names was too quick.
Fields that contain special characters, such as No., must be in quotation as well.
#120
> Bugfix: fields in quotation if they contain special characters

- src/CRSFunctions.ts
- src/UI/CRSStatusBar.ts
- src/extension.ts
Hi Waldo,
I have seen that your extension is subscribed to `vscode.workspace.onDidOpenTextDocument` event. This subscription causes errors when there is no active TextEditor.
First case is no big issue as it happens rarely, but still it should be fixed. :)
Second case, however, can easily become a real performance-killer when [another extension](https://github.com/365businessdev/vscode-alxmldocumentation/blob/7f5aa97165c66408779d3fc0e4e4612073e95949/src/DoCheckDocumentation.ts#L61) decides to read up all AL files via VSCode api, thus emitting `onDidOpenTextDocument` event like 6000 times for a BaseApp.
My proposed solution would be to move your statusbar update code from `workspace.onDidOpenTextDocument` to `window.onDidChangeActiveTextEditor` with some additional error checks to avoid …
> Fixed statusbar error when focusing to webview

- package.json
- src/CRSFunctions.ts
- src/Configuration.ts
- src/extension.ts
Contributed command to configure best-practice file naming in user,
workspace, or individual workspace folder settings file, depending on
current workspace configuration.
The command sets the `FileNamePattern*` options as explained in
https://www.waldo.be/2020/04/03/how-to-really-rename-all-al-files-of-your-business-central-app/
> Best-practice file naming configuration

- src/CRSTerminal.ts
- src/extension.ts
VS Code now preserves terminals between reloads of the window.
The extension creates a new crs terminal each time the window is loaded so you can collect a stack of crs terminals.
> Reuse crs terminal if one already exists

- src/Settings.ts
Fixes #195 
If we are using the file wizard from [al-code-outline](https://github.com/anzwdev/al-code-outline) and we are working with a workspace the settings inside the .vscode/settings.json are not taken into account.
PS: I would have expected ``vscode.workspace.getConfiguration(this.WORKSPACEKEY, null);`` to retrieve all merged configurations by default, not just the default values.
> Search workspace folder for config files

- src/DynamicsNAV.ts
If running a container as multitenant, you get a URL in the format BASE/?tenant=xyz&table=1234
But the command line does not like the ampersand and thus does not work in my chrome, it only opens the base including the tenant thus skipping the rest of the URL. By wrapping the URL in double quotes, the URL is only seen as a string, with or without ampersand.
Hope it will render useful, same applies to Firefox
> Hide ampersand from the commandline

- package.json
- src/CRSFunctions.ts
- src/Settings.ts
When CRS Rename all files is run a question "Are you sure to rename all files from all opened workspaces?" pops up, which is disturbing the custom created visual studio task for compiling the app with all the checks done.
This feature gives the user the possibility to disable this question popup.
> Added option for skipping warning message

- snippets/DesignPatterns.json
Attempts to close #203.
> Use of implicit 'with' will be removed in the future. Qualify with 'Rec'. This warning will become an error in a future release.AL([AL0604](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al604))
> #203 Fix AL0604

- snippets/al.json
This PR attempts to close https://github.com/waldo1001/crs-al-language-extension/issues/236.
I'd also like to point 3 things out here:
1. `Verbosity::${3|Normal,Critical,Error,Verbose,Warning|}`
2. `DataClassification::${4|SystemMetadata,AccountData,CustomerContent,EndUserIdentifiableInformation,EndUserPseudonymousIdentifiers,OrganizationIdentifiableInformation,ToBeClassified|}`
3. `TelemetryScope::${5|ExtensionPublisher,All|}`
The order has been customized in a way that they now start with Normal, SystemMetadata and ExtensionPublisher. This depends on the scenario - so... shall we put it out there as it is and let the users test it? wdyt
> Added Log Message snippet

- .vscodeignore
Remove `node_modules` from `.vscodeignore`
> Hotfix for #245

- src/NAVObject.ts
- src/Settings.ts
- src/test/suite/NAVObject.PrefexAndSuffix.test.ts
- src/test/suite/NAVTestObjectLibrary.ts
This is a first draft to support multiple prefixes.
Right now I added the feature only for table extensions fields.
But this can easily added for the other extension objects.
I was tryin to create a solution for issue: https://github.com/waldo1001/crs-al-language-extension/issues/151
It's not perfect, but I could work as temporary solution.
@waldo1001 do you have any plans and time to work on improvements of prefix handling or would accept the solution that is proposed with this Pull Request.
@christianbraeunlich you do seem to have some experience with npm.
Do you know how I can disable that the yarn.lock is updated and that yarn.lock is used instead of package-lock.json for this repository?
> First draft for Support of multiple Prefixes

- snippets/fromAlExtension/al.json
Hello there,
whenever using this snippet, it just simply doesn't work for me: 4/5 productivity
With theses changes it's easy to TAB all the way to the procedure body (local variables still need to be added later on but thats totaly fine).
hint: if the cursor is on the 3rd, 4th and 5th step => we just press CTRL+SPACE and voilá
(just realized that we could also create some logic to insert all variables of the publisher into the event subscriber. But that's anotter story 🦦)
> Updated snippet: teventsubwaldo 

- src/NAVObject.ts
- src/test/suite/NAVObject.PrefexAndSuffix.test.ts
- src/test/suite/NAVTestObjectLibrary.ts
This pull request, is trying to support Page Extensions with Array as SourceExpression.
Fixes Issue: https://github.com/waldo1001/crs-al-language-extension/issues/260
e.g.
```al
field(ShortcutDimCode4; ShortcutDimCode[4])
{
ApplicationArea = Dimensions;
CaptionClass = '1,2,4';
TableRelation = "Dimension Value".Code WHERE("Global Dimension No." = CONST(4),
"Dimension Value Type" = CONST(Standard),
Blocked = CONST(false));
Visible = DimVisible4;
trigger OnValidate()
begin
ValidateShortcutDimension(4);
end;
}
```
> #260 Add Support for Arrays on Page Extensions

- snippets/install.json
- snippets/upgrade.json
I have been using your snippets for upgrade and install codeunit a lot lately and ended up doing the sames changes all the time.
Maybe you agree with my changes and we can merge them ;)
- I usually create multiple upgrade procedures in the same upgrade codeunit, so I do the handling of the tags inside the procedure and just do a bunch of function calls in the upgrade trigger
- The HasUpgradeTag and SetUpgradeTag procedures do automatically grab the current company name, and the company name is part of the PK on the table that stores the tags. No need to included into the tag itsself
EDIT: Seems like the Company could also mean the company doing the development. So I added it back but called it "PublisherAffix"
- I only want to set the upgrade tags on install when doing a fresh install of …
> Minor changes to Upgrade Snippet Logic

- README.md
- package.json
- src/NAVObject.ts
- src/Settings.ts
- src/WorkspaceFiles.ts
- src/test/suite/NAVTestObjectLibrary.ts
- src/test/suite/WorkspaceFiles.test.ts
#291 
This is a feature that allows for the automatic reorganization of files by creating folder structures based on the namespaces defined within the files.
> Reorganize By Namespace

- src/StringFunctions.ts
- src/test/suite/NAVObject.PrefexAndSuffix.test.ts
- src/test/suite/NAVTestObjectLibrary.ts
In AL Code, it is required that any field name starting with an integer is wrapped in double quotes. If not, then the compiler throws a huge fit.
When saving a file, the CRS language extension currently removes quotes from these field names, resulting in uncompilable code. Even if using ">Save without formatting", the CRS extension still removes the quotes. This problem is described in #153 
This fix changes the `StringFunctions.encloseInQuotesIfNecessary` method to also recognize such field names and enclose them in quotation marks.
> Use quotes around field names that start with an integer

- src/NAVObject.ts
- src/test/suite/NAVObject.PrefexAndSuffix.test.ts
- src/test/suite/NAVTestObjectLibrary.ts
#293 caused a side-effect where the ID of table fields would sometimes get wrapped in double quotes.
This change makes it so that only the relevant `AddPrefixAndSuffix` methods get called for the object type. For example, the logic to fix page fields will not get called on table objects or tableextension objects.
> Fix issue where table field IDs get quoted if field name contains special chars

- README.md
- package.json
- src/NAVObject.ts
- src/Settings.ts
- src/WorkspaceFiles.ts
New setting: NamespacePrefixToIgnore
This configuration allows you to exclude a part of Namespace during the files reorganization process based on the namespaces defined within the files
> Exclude Namespace prefix

- src/NAVObject.ts
- src/test/suite/NAVObject.PrefexAndSuffix.test.ts
- src/test/suite/NAVTestObjectLibrary.ts
Don't add affix if object name contains one of the MandatoryAffixes.
I added the affix check to then Name of the Object, the PageField and thePageAction
Fixes #279
> Add Support for AppSourceCop Setting MandatoryAffixes

- src/NAVObject.ts
Don't add affix if object name contains one of the MandatoryAffixes.
I added the affix check to then Name of the Object
> Add Affix Check for Object Name
